spring:
  application:
    name: eureka-server

server:
  port: 10003

eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:10001/eureka/,http://peer2:10002/eureka/
