spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/htzhu/spring-cloud-config.git

server:
  port: 1202

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://qrshi7:10001/eureka/

